// https://leetcode.com//problems/find-the-difference/#/description		 QuestionId:389
import java.io.*; 
import java.util.*; 
public class Solution {
    /*
    public char findTheDifference(String s, String t) {
        int [] map = new int[26];
        
        for(int i =0; i < s.length(); i++) 
            map[s.charAt(i) - 'a']++;

        for(int i =0; i < t.length(); i++) 
            if(map[t.charAt(i) - 'a'] > 0)
                map[t.charAt(i) - 'a']--;
            else 
                map[t.charAt(i) - 'a']++;
                
        for(int i=0; i < t.length(); i++)
            if(map[t.charAt(i) - 'a'] == 1)
                return t.charAt(i);
        
        return 0;
    }
    */
    
    public char findTheDifference(String s, String t) {
	int n = t.length();
	char c = t.charAt(n - 1);
	for (int i = 0; i < n - 1; ++i) {
		c ^= s.charAt(i);
		c ^= t.charAt(i);
	}
	return c;
}
}
/*----------------------------------------------------------------------------------- 
 Problem: 

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/